"""Rule catalog — reads and caches the native/OPA rule metadata.

The gateway does NOT import apme_engine at runtime. For V1 the rule catalog
is loaded from the RULE_CATALOG.md documentation file (which is generated by
scripts/generate_rule_catalog.py) and from the rules embedded in the proto
stubs.  A future version may add a ``ListRules`` RPC to Primary.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

_RULE_LINE_RE = re.compile(
    r"^\|\s*(?P<rule_id>[A-Z]+\d+)\s*\|\s*(?P<validator>[^|]+)\|\s*(?P<desc>[^|]+)\|\s*(?P<fixer>[^|]*)\|",
)


@dataclass
class RuleInfo:
    """Metadata for a single rule."""

    rule_id: str
    description: str
    level: str = "warning"
    validator: str = ""
    fixable: bool = False
    scope: str = ""
    tags: list[str] = field(default_factory=list)


_cache: list[RuleInfo] | None = None


def _parse_catalog(catalog_path: Path) -> list[RuleInfo]:
    """Parse RULE_CATALOG.md into RuleInfo objects.

    Args:
        catalog_path: Path to the markdown rule catalog.

    Returns:
        List of parsed RuleInfo objects.
    """
    rules: list[RuleInfo] = []
    if not catalog_path.is_file():
        logger.warning("Rule catalog not found at %s", catalog_path)
        return rules

    for raw_line in catalog_path.read_text(encoding="utf-8").splitlines():
        m = _RULE_LINE_RE.match(raw_line)
        if not m:
            continue
        rule_id = m.group("rule_id").strip()
        validator = m.group("validator").strip()
        desc = m.group("desc").strip()
        fixer = m.group("fixer").strip()

        rules.append(
            RuleInfo(
                rule_id=rule_id,
                description=desc,
                validator=validator.lower(),
                fixable=fixer.lower() in ("yes", "true", "✓"),
            ),
        )
    return rules


def load_rules(catalog_path: Path | None = None) -> list[RuleInfo]:
    """Load or return cached rule catalog.

    Args:
        catalog_path: Override path; defaults to docs/RULE_CATALOG.md
            relative to the repo root.

    Returns:
        List of RuleInfo objects.
    """
    global _cache  # noqa: PLW0603
    if _cache is not None:
        return _cache

    if catalog_path is None:
        candidates = [
            Path(__file__).resolve().parents[3] / "docs" / "RULE_CATALOG.md",
            Path("/app/docs/RULE_CATALOG.md"),
        ]
        for c in candidates:
            if c.is_file():
                catalog_path = c
                break

    if catalog_path is None:
        logger.warning("No RULE_CATALOG.md found; rule catalog will be empty")
        _cache = []
        return _cache

    _cache = _parse_catalog(catalog_path)
    logger.info("Loaded %d rules from %s", len(_cache), catalog_path)
    return _cache


def get_rule(rule_id: str) -> RuleInfo | None:
    """Look up a single rule by ID.

    Args:
        rule_id: Rule identifier (e.g. ``L002``).

    Returns:
        RuleInfo or None.
    """
    for r in load_rules():
        if r.rule_id == rule_id:
            return r
    return None
