"""Database models and Pydantic schemas for the APME gateway."""

from apme_gateway.models.database import Base, RemediationProposal, ScanRecord, ViolationRecord
from apme_gateway.models.schemas import (
    DiagnosticsOut,
    FixCreate,
    FixJobStatus,
    FormatDiffOut,
    FormatRequest,
    HealthOut,
    PaginatedResponse,
    RemediationAction,
    RemediationOut,
    RuleDetail,
    RuleOut,
    ScanCreate,
    ScanDetail,
    ScanSummary,
    ServiceHealth,
    ValidatorDiagnosticsOut,
    ViolationOut,
)

__all__ = [
    "Base",
    "ScanRecord",
    "ViolationRecord",
    "RemediationProposal",
    "ScanCreate",
    "ScanSummary",
    "ScanDetail",
    "ViolationOut",
    "RuleOut",
    "RuleDetail",
    "FixCreate",
    "FixJobStatus",
    "RemediationOut",
    "RemediationAction",
    "FormatRequest",
    "FormatDiffOut",
    "HealthOut",
    "ServiceHealth",
    "DiagnosticsOut",
    "ValidatorDiagnosticsOut",
    "PaginatedResponse",
]
