# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apme/v1/plugin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'apme/v1/plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2
from apme.v1 import validate_pb2 as apme_dot_v1_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pme/v1/plugin.proto\x12\x07\x61pme.v1\x1a\x14\x61pme/v1/common.proto\x1a\x16\x61pme/v1/validate.proto\"\x85\x01\n\x10TransformRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x1b\n\x04\x66ile\x18\x02 \x01(\x0b\x32\r.apme.v1.File\x12%\n\tviolation\x18\x03 \x01(\x0b\x32\x12.apme.v1.Violation\x12\x19\n\x11hierarchy_payload\x18\x04 \x01(\x0c\"d\n\x11TransformResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x1b\n\x04\x66ile\x18\x02 \x01(\x0b\x32\r.apme.v1.File\x12\x0f\n\x07\x61pplied\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x11\n\x0f\x44\x65scribeRequest\"\xd1\x01\n\x10\x44\x65scribeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0erule_id_prefix\x18\x03 \x01(\t\x12\x1a\n\x12transform_rule_ids\x18\x04 \x03(\t\x12\x39\n\x08metadata\x18\x05 \x03(\x0b\x32\'.apme.v1.DescribeResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x89\x02\n\x06Plugin\x12?\n\x08Validate\x12\x18.apme.v1.ValidateRequest\x1a\x19.apme.v1.ValidateResponse\x12\x42\n\tTransform\x12\x19.apme.v1.TransformRequest\x1a\x1a.apme.v1.TransformResponse\x12?\n\x08\x44\x65scribe\x12\x18.apme.v1.DescribeRequest\x1a\x19.apme.v1.DescribeResponse\x12\x39\n\x06Health\x12\x16.apme.v1.HealthRequest\x1a\x17.apme.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apme.v1.plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIBERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_DESCRIBERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TRANSFORMREQUEST']._serialized_start=80
  _globals['_TRANSFORMREQUEST']._serialized_end=213
  _globals['_TRANSFORMRESPONSE']._serialized_start=215
  _globals['_TRANSFORMRESPONSE']._serialized_end=315
  _globals['_DESCRIBEREQUEST']._serialized_start=317
  _globals['_DESCRIBEREQUEST']._serialized_end=334
  _globals['_DESCRIBERESPONSE']._serialized_start=337
  _globals['_DESCRIBERESPONSE']._serialized_end=546
  _globals['_DESCRIBERESPONSE_METADATAENTRY']._serialized_start=499
  _globals['_DESCRIBERESPONSE_METADATAENTRY']._serialized_end=546
  _globals['_PLUGIN']._serialized_start=549
  _globals['_PLUGIN']._serialized_end=814
# @@protoc_insertion_point(module_scope)
