# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2
from apme.v1 import plugin_pb2 as apme_dot_v1_dot_plugin__pb2
from apme.v1 import validate_pb2 as apme_dot_v1_dot_validate__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apme/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginStub:
    """Plugin is the third-party extension contract (ADR-042).
    Separate from Validator so built-in validators stay read-only (ADR-009).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/apme.v1.Plugin/Validate',
                request_serializer=apme_dot_v1_dot_validate__pb2.ValidateRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_validate__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Transform = channel.unary_unary(
                '/apme.v1.Plugin/Transform',
                request_serializer=apme_dot_v1_dot_plugin__pb2.TransformRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_plugin__pb2.TransformResponse.FromString,
                _registered_method=True)
        self.Describe = channel.unary_unary(
                '/apme.v1.Plugin/Describe',
                request_serializer=apme_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_plugin__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/apme.v1.Plugin/Health',
                request_serializer=apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class PluginServicer:
    """Plugin is the third-party extension contract (ADR-042).
    Separate from Validator so built-in validators stay read-only (ADR-009).
    """

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=apme_dot_v1_dot_validate__pb2.ValidateRequest.FromString,
                    response_serializer=apme_dot_v1_dot_validate__pb2.ValidateResponse.SerializeToString,
            ),
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=apme_dot_v1_dot_plugin__pb2.TransformRequest.FromString,
                    response_serializer=apme_dot_v1_dot_plugin__pb2.TransformResponse.SerializeToString,
            ),
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=apme_dot_v1_dot_plugin__pb2.DescribeRequest.FromString,
                    response_serializer=apme_dot_v1_dot_plugin__pb2.DescribeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=apme_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=apme_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apme.v1.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apme.v1.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin:
    """Plugin is the third-party extension contract (ADR-042).
    Separate from Validator so built-in validators stay read-only (ADR-009).
    """

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Plugin/Validate',
            apme_dot_v1_dot_validate__pb2.ValidateRequest.SerializeToString,
            apme_dot_v1_dot_validate__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Plugin/Transform',
            apme_dot_v1_dot_plugin__pb2.TransformRequest.SerializeToString,
            apme_dot_v1_dot_plugin__pb2.TransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Plugin/Describe',
            apme_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
            apme_dot_v1_dot_plugin__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Plugin/Health',
            apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
